version: "3.1"

volumes:
  mongo-data: {}

services:
  db:
    container_name: mongoDB
    image: mongo
    volumes:
      - "mongo-data:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=Pokemon
    ports:
      - 27018:27018
    restart: always